### ISSUE TITLE
(BUG) ItemDropMode current requires item to square up

### ISSUE THREAD

**Issue by TheComicRelief** [ThomasNg2/LethalHands#6]
Choosing the current option in itemdropmode only allows me to square up when i hold something in hand (not inventory). All and none options tested and didn't seem to cause any issues.

**Comment by ThomasNg2** [comment]
Oh yeah, the method I used to drop only the current item expects you to have one in the first place, and it throws an error if you don't, cancelling the input.

Thanks for letting me know, fixed in 22.0.10
