### ISSUE TITLE
LethalHands are not working on version 56

### ISSUE THREAD

**Issue by spiritofthemeat** [ThomasNg2/LethalHands#7]
I uninstalled and reinstalled but didn't work. Keep pressing any key including J but couldn't punch anything. Would be great if you check the bug asap. Love your work <3

**Comment by ThomasNg2** [comment]
The culprit seems to be MikesTweaks which fails to load (probably because it's outdated) and in doing so it takes down my mod as well because both mods try to modify the same component. Even on its own (just MikesTweaks and BepInEx) it fails to load.

**Comment by spiritofthemeat** [comment]
I just uninstalled MikeTweaks and it worked! Everything goes well w.o the mod :) Thanks for your help !
