### ISSUE TITLE
Probability get off

### ISSUE THREAD

**Issue by Xeraccoon** [ThomasNg2/LethalHands#8]
Hi, thx for your wonderfull plugin, do you think you can add, Probability stats get off the head snare and other small creature, actually we have only dammage or 100% luck remove it ( it's little broken and i want to be little more fair, or if you can add nomber of time we can remove him from the head.

**Comment by ThomasNg2** [comment]
ye could turn the on/off config to a % instead

**Comment by Xeraccoon** [comment]
where ? i can define % snare leave my head per hit ? i see it nowhere

**Comment by ThomasNg2** [comment]
Sorry for the possible misunderstanding, in my last comment I was talking about adding your suggestion to the next update, which I've just uploaded (give it some time to appear on mod managers if you're using one of those).

Let me know if that's what you wanted, and feel free to close the issue if yes.

**Comment by Xeraccoon** [comment]
ok, sorry it was me who misunderstood ^^ thanks for the reactivity! yes that's exactly what I was looking for, over the top! thx
